---
title: 'Class 6: R functions'
author: "Barry Grant"
date: "4/19/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview
Today we will focus on **R functions** but we will start with a bit of **file reading**.

```{r}
plot(1:10, type="l", col="blue")
```

```{r}
read.table("test1.txt", header=TRUE, sep=",")
```

I am going to see if I can open the other example files by setting the appropriate arguments to the functions...


```{r}
read.table("test2.txt", sep="$", header=TRUE)
```

```{r}
read.table("test3.txt")
```

```{r}
read.csv("https://bioboot.github.io/bggn213_S19/class-material/test1.txt")
```


## Our first function

Add some numbers


```{r}
add <- function(x, y=1) {
  # The body
  x + y
}
```

```{r}
add(4, y=5)
```

```{r}
add( c(1,3,5), 1)
```

```{r}
add( c(1,3,5) )
```

```{r}
#add( 1, 3, 5)
```

```{r}
#add(x=1, y="barry")
```

```{r}
add(4)
```

## our 2nd example function

```{r}
rescale <- function(x) {
   rng <-range(x)
   (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale( c(1, 3, NA, 5, 10) )
```

```{r}
x <- c(1, 3, NA, 5, 10)
rng <-range(x, na.rm=TRUE)
rng
(x - rng[1]) / (rng[2] - rng[1])

```


```{r}
rescale2 <- function(x, na.rm=TRUE) {
   rng <-range(x, na.rm=na.rm)
   (x - rng[1]) / (rng[2] - rng[1])
}

```

```{r}
rescale2( c( 1,3,NA,10) )
```

```{r}
#rescale2( c(1,3,"barry",10) )
```


```{r}
rescale( 1:10 )
```



Anoter example extension 

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {

    rng <-range(x, na.rm=na.rm)
    print("Hello")

   answer <- (x - rng[1]) / (rng[2] - rng[1])

   
   print("is it me you are looking for?")

   if(plot) { 
      plot(answer, typ="b", lwd=4) 
     print("Dont sing please!!!")
   }
   print("I can see it in ...")
   return(answer)

}
```

```{r}
rescale3( 1:10 )
```

```{r}
rescale3( 1:10, plot=TRUE)
```

# Section 1B Hands-on

```{r}
library(bio3d)
pdb <- read.pdb("4AKE")
```

```{r}
is.vector(pdb)
```

```{r}
is.data.frame(pdb)
```


```{r}
is.list(pdb)
```

```{r}
pdb$seqres
```


```{r}
s1 <- read.pdb("4AKE")
s1
```

```{r}
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.chainA
```

```{r}
s1.b <- s1.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
```


```{r}
plotb3(s1.b, typ="l", ylab="Bfactor")

```





```{r}
s1 <- read.pdb("4AKE")  # kinase with drug
s2 <- read.pdb("1AKE")  # kinase no drug
s3 <- read.pdb("1E4Y")  # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

```{r}
rbind( 1:10, 1:10, 1:10) 
```


```{r}
hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) )
plot(hc)
```




```{r}
# Dont ever start like this
makeplot <- function(x) {
  s1 <- read.pdb(x)  # kinase with drug

}
```












